# Package Overview
package_name: regression_model

# Data Files
training_data_file: titanic.csv
test_data_file: titanic.csv


target: survived

pipeline_name: titanic_pipe
pipeline_save_file: model


# Intendention matters in yml and here a key with intended dash is the list 
features:
pclass	
survived	
sex	
age	
sibsp	
parch	
fare	
cabin	
embarked	
title

  

# set train/test split
test_size: 0.2

# to set the random seed
random_state: 0

alpha: 0.001

# categorical variables with NA in train set
categorical_vars_with_na_frequent:
  - cabin
 

numerical_vars_with_na:
  - age


ref_var: survived

numerical_vars:
   pclass      
  survived      
  age         
  sibsp         
  parch         
  fare 



categorical_vars:
sex            
cabin       
embarked      
title  

